---
title: "How Well Are we Housed?"
format: html
toc: true
editor: visual
---

## Description

Housing conditions and measures can help us understand why and how housing matters. This week, we'll examine foundational evidence for how well we are housed in the United States, and will examine some of the common discourses and factors surrounding policy debates around housing.

## Learning Goals

-   Develop a basic understanding of the housing delivery and regulatory system in the United States.
-   Articulate the nature of key discourses regarding housing production and consumption.
-   Become familiar with key indicators and measures of housing supply and consumption in the United States.

## Readings

-   [Assignment 1 Prompt](../assignments/01_intersection.qmd)

-   Harvard Joint Center for Housing Studies State of the Nation's Housing (2023)   [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/eojp0fu6ukfa04v6pgca53jxm4l43x2w)   [{{< fa globe >}}](https://www.jchs.harvard.edu/state-nations-housing-2023)

Read the Executive Summary plus the additional chapter you are assigned below:

### JCHS Reading Assignments

1.  Executive Summary - Everyone

2.  Housing Markets

-   Hyndavi A.
-   Ar'Mand E.
-   Janet H.
-   Jenifer M.
-   Aabha S.
-   Michael V.

3.  Demographic Drivers

-   Leela B.
-   Cole F.
-   Shinmyeon H.
-   Anjana N.
-   Ellie S.
-   Yingqi Y.

4.  Homeownership

-   Emma B.
-   Dasom H.
-   Nadia K.
-   Rose R.K.
-   Priya S.
-   Zhenpeng Z.

5.  Rental Housing

-   Karley C.
-   Prithvi H.
-   Trinity L.
-   Maria R.S.
-   Shiva S.

6.  Housing Challenges

-   Julia P.
-   Hexiang H.
-   Anukriti M.
-   Celio R.M.
-   Andrew S.
-   Jerry R.

## Slides

## In Class

Collective Slide Deck (Open in Box using PowerPoint Online so we can edit at the same time) [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/4g06ds8uwakcomwrbkxg432taowywsgr)

## Additional Resources

-    [A Refugee Crisis Runs Into a Housing Crisis](https://www.nytimes.com/2021/12/15/us/afghan-refugees-housing.html)

-    [Cizek, Katerina, \*A Short History of the Highrise](https://www.nytimes.com/video/opinion/100000002465058/a-short-history-of-the-highrise-part-1.html?playlistId=100000001150263)

-    [How Austin Became one of the Least Affordable Cities in America](https://www.nytimes.com/2021/11/27/us/austin-texas-unaffordable-city.html)

-    [In Bakersfield, Many Find a California They Can Afford](https://www.nytimes.com/2021/12/11/us/california-housing-bakersfield.html)

-    [Selling Luxury Condos Where Oliver Twist Once Asked for Gruel](https://www.nytimes.com/2021/12/23/business/dickens-condos-oliver-twist-workhouse.html?campaign_id=61&emc=edit_ts_20211223&instance_id=48588&nl=the-great-read&regi_id=70210024&segment_id=77801&te=1&user_id=9f9ec940111719362bb03c71463df3a8)
