---
title: "Policy Analysis"
format: html
toc: true
editor: visual
---

## Description

In this session, we will examine a range of frameworks for policy analysis. We have now developed a broad understanding of the structure, function, and broader policy and economic questions associated with housing and urban policy. As we transition into looking at more specific policy approaches, this session is designed to help us think through frameworks for analyzing the rationale for policies, their design politics, their implementation, and associated outcomes.

## Learning Goals

-   Gain exposure to common frameworks for policy analysis.
-   Think critically about how to apply these common frameworks to specific policies.
-   Think about how to communicate the results of policy analysis to a broad audience.

## Readings

Knoepfel, Peter, Corinne Larue, Frederic Varone, and Michael Hill. 2007. *Public Policy Analysis*. Bristol University Press.   [{{< fa globe >}}](https://www-jstor-org.proxy2.library.illinois.edu/stable/j.ctt9qgz7q)

-   Chapter 2: Public Policy   [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/14jp21t3kcl03pnf20vv2jki05x2vqok)   [{{< fa globe >}}](https://www-jstor-org.proxy2.library.illinois.edu/stable/j.ctt9qgz7q.8)

-   Chapter 3: Policy Actors   [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/ntonk7h8x0yun1yoifxy4w9nafqhz5vg)   [{{< fa globe >}}](https://www-jstor-org.proxy2.library.illinois.edu/stable/j.ctt9qgz7q.9)

-   Chapter 4: Policy Resources   [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/7rc6ed239bim50imerhxcp4yuxbw602t)   [{{< fa globe >}}](https://www-jstor-org.proxy2.library.illinois.edu/stable/j.ctt9qgz7q.10)

## Reflect

1.  What's the relationship between policy making, policy implementation, and policy analysis?

2.  What particular challenges arise when analyzing housing policies?

3.  What social questions inform housing policy analysis in 2023?

## Slides

[Session 5 Slide Deck](https://uofi.box.com/s/so9s3mgtdvdxrsaj55o7050alf3yeb1k)
## In Class

Collective Slide Deck (Open in Box using PowerPoint Online so we can edit at the same time) [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/ua063iboz4pl7xa217nphxcdfy833zlx)

## Additional Resources
