---
title: "Reading Week"
format: html
toc: true
editor: visual
---

## Description

This week, we will not meet as a class - instead you will work in your discussion facilitation groups to shape your facilitation of the course module which you are assigned to work on.

## Prompt

Please refer to the [discussion facilitation assignment](../assignments/05_facilitation.qmd) and associated [template](../assignments/Module_Plan_Template.docx) to work through your module preparations this week.

Your group should also request a meeting with Professor Greenlee this week to discuss your plans.

## Assigned Groups

### How are individual and collective financial benefits and burdens allocated through housing?

Karley C.</br>
Cole F.</br>
Hexiang H.</br>
Anjana N.</br>
Aabha S.</br>
Yingqi Y.</br>

[Sessions](../schedule/#how-are-individual-and-collective-financial-benefits-and-burdens-allocated-through-housing)

### Where are poor people to live? What housing are poor people to occupy?

Emma B.</br>
Ar'Mand E.</br>
Shinmyeong H.</br>
Rose R.K.</br>
Elle S.</br>
Michael V.</br>

[Sessions](../schedule/#where-are-poor-people-to-live-what-housing-are-poor-people-to-occupy)

### How do neighborhoods matter for economic and social mobility?

Leela, B.</br>
Dasom H.</br>
Nadia K.</br>
Anukriti M.</br>
Jerry R.</br>
Zhenpeng Z.</br>

[Sessions](../schedule/#how-do-neighborhoods-matter-for-economic-and-social-mobility)

### What are the causes and consequences of housing instability?

Hyndavi A.</br>
Prithvi H.</br>
Janet H.</br>
Jenifer M.</br>
Priya S.</br>
Andrew S.</br>

[Sessions](../schedule/#what-are-the-causes-and-consequences-of-housing-instability)

### What would a global right to housing look like?

Sepideh A.</br>
Julia P.</br>
Trinity L.</br>
Maria R.S.</br>
Shiva S.</br>

[Sessions](../schedule/#what-would-a-global-right-to-housing-look-like)