---
title: "Dr. Natalie Prochaska"
format: html
toc: true
editor: visual
---

## Description

Today, we'll be joined by [Dr. Natalie Prochaska](https://www.linkedin.com/in/natalie-prochaska-phd-250a0916/), Director of Planning and Research at [Nevada HAND](https://nevadahand.org). Natalie received her MUP and Ph.D. from University of Illinois at Urbana-Champaign. 

Dr. Prochaska is an expert on community development finance, and has worked closely with community development financial institutions to support the development of affordable housing. Through our conversation with Natalie, we will talk more about the ways in which these institutions support the development and continued operation of affordable housing.

## Learning Goals

-   Develop an understanding of homeownership as simultaneously a material and political project in the United States.
-   Understand the evolution of key financial mechanisms that underscore homeownership.
-   Articulate some of the risks and rewards associated with owner-occupied housing.

## Readings

Rethinking Homeownership as the American Dream  [{{< fa arrow-up-right-from-square >}}](https://uofi.box.com/s/se23crvw6y9ro3btz5o7aoclq19igeat)   [{{< fa globe >}}](https://www.urban.org/urban-wire/rethinking-homeownership-american-dream)

## Slides

## Additional Resources

-   
