---
title: "Schedule"
format: html
toc: false
editor: visual
---

Our course schedule is subject to change over the course of semester - please check here often for updates.

## How will we learn together? How can we conceptualize the impacts of housing and urban policy?

+------------------+---------------------------------------------+
| Date             | Topic                                       |
+==================+=============================================+
| 8/21/2023        | [Course Introduction](01_introduction.qmd)  |
+------------------+---------------------------------------------+
| 8/23/2023        | [Conceptual Frameworks for Housing Analysis](02_conceptual.qmd)  |
+------------------+---------------------------------------------+

## How well are we housed?

+-----------------+---------------------------------------------------------+
| Date            | Topic                                                   |
+=================+=========================================================+
| 8/28/2023       | [How well are we housed?](03_housed.qmd)                |
+-----------------+---------------------------------------------------------+
| 8/30/2023       | [Government intervention in housing](04_government.qmd) |
+-----------------+---------------------------------------------------------+
| 9/6/2023        | Housing policy analysis                                 |
+-----------------+---------------------------------------------------------+

## Reading Week

+------------------+---------------------------------------------+
| Date             | Topic                                       |
+==================+=============================================+
| 9/11/2023        | Reading Week - No Class Session             |
+------------------+---------------------------------------------+
| 9/13/2023        | Reading Week - No Class Session             |
+------------------+---------------------------------------------+

## How are individual and collective financial benefits and burdens allocated through housing?

+------------------+---------------------------------------------+
| Date             | Topic                                       |
+==================+=============================================+
| 9/18/2023        | Homeownership                               |
+------------------+---------------------------------------------+
| 9/20/2023        |                                             |
+------------------+---------------------------------------------+
| 9/25/2023        | Housing Finance                             |
+------------------+---------------------------------------------+
| 9/27/2023        |                                             |
+------------------+---------------------------------------------+

## Where are poor people to live? What housing are poor people to occupy?

+-------------------+------------------------------------------------+
| Date              | Topic                                          |
+===================+================================================+
| 10/2/2023         | Public Housing                                 |
+-------------------+------------------------------------------------+
| 10/4/2023         | Federally Assisted Housing                     |
+-------------------+------------------------------------------------+
| 10/9/2023         | Housing Production Strategies                  |
+-------------------+------------------------------------------------+
| 10/11/2023        |                                                |
+-------------------+------------------------------------------------+

## How do neighborhoods matter for economic and social mobility?

+-------------------+------------------------------------------------+
| Date              | Topic                                          |
+===================+================================================+
| 10/16/2023        | The Enduring Significance of Neighborhoods     |
+-------------------+------------------------------------------------+
| 10/18/2023        | No Class - ACSP Conference                     |
+-------------------+------------------------------------------------+
| 10/23/2023        | Neighborhood Change                            |
+-------------------+------------------------------------------------+
| 10/25/2023        |                                                |
+-------------------+------------------------------------------------+

## What are the causes and consequences of housing instability?

+-------------------+------------------------------------------------+
| Date              | Topic                                          |
+===================+================================================+
| 10/30/2023        | Eviction                                       |
+-------------------+------------------------------------------------+
| 11/1/2023         | Regulating Housing Environments                |
+-------------------+------------------------------------------------+
| 11/6/2023         | Landscapes of Housing Risk                     |
+-------------------+------------------------------------------------+
| 11/8/2023         |                                                |
+-------------------+------------------------------------------------+

## What would a global right to housing look like?

+-------------------+------------------------------------------------+
| Date              | Topic                                          |
+===================+================================================+
| 11/13/2023        | Housing Market Discrimination and Fair Housing |
+-------------------+------------------------------------------------+
| 11/15/2023        | Housing Special Populations                    |
+-------------------+------------------------------------------------+
| 11/20/2023        | Fall Break - No Class                          |
+-------------------+------------------------------------------------+
| 11/22/2023        | Fall Break - No Class                          |
+-------------------+------------------------------------------------+
| 11/27/2023        | The Paradox of Housing Inclusion               |
+-------------------+------------------------------------------------+
| 11/29/2023        |                                                |
+-------------------+------------------------------------------------+

## What's your plan for intervention?

+-------------------+------------------------------------------------+
| Date              | Topic                                          |
+===================+================================================+
| 12/4/2023         | Final Presentations                            |
+-------------------+------------------------------------------------+
| 12/6/2023         | Final Presentations                            |
+-------------------+------------------------------------------------+

+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week    | Dates   |         | Description                                                          | Discussant(s) |
+=========+=========+=========+======================================================================+===============+
| Week 1  | 1/18/23 |         |                                                                      |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 2  | 1/23/23 | 1/25/23 |                                                                      |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 3  | 1/30/23 | 2/1/23  |                                                                      |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 4  | 2/6/23  | 2/8/23  | [Homeownership](04_homeownership.qmd)                                | Tillie        |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Dorian        |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 5  | 2/13/23 | 2/15/23 | [Public Housing](05_publichousing.qmd)                               | Zane          |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 6  | 2/20/23 | 2/22/23 | [Federally Assisted Housing](06_fedassisted.qmd)                     | Erica         |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 7  | 2/27/23 | 3/1/23  | [Housing Production Strategies](07_production.qmd)                   | Rafi          |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Temka         |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 8  | 3/6/23  | 3/8/23  | [The Enduring Significance of Neighborhoods](08_neighborhoods.qmd)   | Fatima        |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Juliana       |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 9  | 3/13/23 | 3/15/23 | [Spring Break](09_break.qmd)                                         |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 10 | 3/20/23 | 3/22/23 | [Regulating Housing Environments](10_hsgenv.qmd)                     | Margaret      |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 11 | 3/27/23 | 3/29/23 | [Eviction](11_eviction.qmd)                                          | Fiona         |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Daisy         |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 12 | 4/3/23  | 4/5/23  | [Neighborhood Change](12_neighborhoodchg.qmd)                        | Colt          |
|         |         |         |                                                                      |               |
|         |         |         |                                                                      | Caelin        |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 13 | 4/10/23 | 4/12/23 | [Housing Market Discrimination and Fair Housing](13_fairhousing.qmd) | Dominique     |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 14 | 4/17/23 | 4/19/23 | [Housing Special Populations](14_specialpop.qmd)                     |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 15 | 4/24/23 | 4/26/23 | [Independent Work and Advising](15_indwork.qmd)                      |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
| Week 16 | 5/1/23  | 5/3/23  | [Class Presentations and Course Wrap-Up](16_wrapup.qmd)              |               |
+---------+---------+---------+----------------------------------------------------------------------+---------------+
